###ThymeLeaf配置
spring:
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    suffix: .html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false  #关闭缓存
    #配置模板路径,默认是templates,可以不用配置
#    prefix: classpath:templates #在这里作为前缀,表示被thymeleaf修饰的页面在这里作为根目录.注意:不是静态资源）
  mvc:
    static-path-pattern: /** #表示所有的访问都经过静态资源路径
  resources:
    static-locations: classpath:/static/ #在这里表示配置静态资源根路径
